### ISSUE TITLE
LICENSE file states wrong copyright holders

### ISSUE THREAD

**Issue by mauro3** [YWang-east/course-101-0250-00-FinalProject#2]

**Comment by luraess** [comment]
@YWang-east  can you adapt the license file to feature your name only as we reference your repo in one of our publication and want to grant you appropriate credit 🙏

**Comment by YWang-east** [comment]
@luraess hi Ludovic, I have adapted the license. It's nice to know my repo can be of help:)

**Comment by mauro3** [comment]
Tnx!
